---
- name: Provision focal on wsl
  hosts: localhost
  connection: local
  become: true
  vars:
    github_pat: ""
    master_password: ""

  tasks:
    - name: install aptitude and `apt update`
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: install apt packages
      apt:
        pkg:
          - git
          - curl
          - wget
          - gettext
          - gawk
          - tree
          - gnupg
          - gnupg2
          - ca-certificates
          - lsb-release
          - software-properties-common
          - apt-transport-https
          - build-essential
          - htop

          # network utilities
          - net-tools
          - nmap
          - ngrep
          - ncat
          - nethogs
          - cifs-utils
          - whois
          - iftop
          - bmon

          # shell
          - zsh
          - tmux

          # editors
          - nano

          # python
          - python3-pip
          - virtualenv
          - python3-setuptools

          # misc
          - jq
          - imagemagick
          - ffmpeg
          - p7zip-full
        state: latest

    - name: shell setup
      block:
        - name: install zsh
          apt:
            pkg: zsh
            state: latest
            update_cache: true

        - name: install oh-my-zsh
          shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

        - name: install Powerlevel10k
          git:
            repo: https://github.com/romkatv/powerlevel10k.git
            dest: "{ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
            depth: 1
            single_branch: true

        - name: install zsh-autosuggestions
          git:
            repo: https://github.com/zsh-users/zsh-autosuggestions.git
            dest: "{ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions"
            depth: 1
            single_branch: true

        - name: install zsh-artisan
          git:
            repo: https://github.com/jessarcher/zsh-artisan.git
            dest: "{ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/artisan"
            depth: 1
            single_branch: true
